version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=${DOCKER_COMPOSE_DJANGO_SECRET_KEY}"
      - "DJANGO_DEBUG=${DOCKER_COMPOSE_DJANGO_DEBUG}"
      - "ZARINPAL_MERCHANT_ID=${DJANGO_COMPOSE_ZARINPAL_MERCHANT_ID}"

  db:
    image: postgres:15.3
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"