# Generated by Django 4.2.3 on 2023-07-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='text',
            field=models.TextField(max_length=3000),
        ),
    ]
