# Generated by Django 4.2.3 on 2023-07-31 08:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_productcomment_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductComment',
            new_name='Comment',
        ),
    ]
